mod auto_config;
mod capabilities;
mod catalog_state;
mod cognitive_runtime;
mod config;
mod mcp;
mod memory;
mod mirrors;
mod provider;
mod runtime;
mod runtime_paths;
mod skill_router;
mod task_manager;
mod update;

pub use auto_config::AutoConfigIntent;
pub use auto_config::AutoConfigResult;
pub use auto_config::apply_auto_config;
pub use auto_config::detect_auto_config;
pub use auto_config::update_installed_skill;
pub use capabilities::*;
pub use catalog_state::ConfiguredMcp;
pub use catalog_state::InstalledSkill;
pub use catalog_state::list_configured_mcp;
pub use catalog_state::list_installed_skills;
pub use catalog_state::remove_configured_mcp;
pub use catalog_state::remove_installed_skill;
pub use catalog_state::set_mcp_enabled;
pub use catalog_state::set_skill_enabled;
pub use cognitive_runtime::*;
pub use config::DEFAULT_CONTEXT_WINDOW;
pub use config::ModelChoice;
pub use config::ProviderConfig;
pub use config::ProviderDocument;
pub use config::ProviderKind;
pub use config::ProviderRegistry;
pub use config::ProviderSettings;
pub use config::RemoteCompactionMode;
pub use mcp::McpRuntime;
pub use mcp::McpServerStatus;
pub use memory::Memory;
pub use memory::MemoryLifecycle;
pub use memory::MemoryManager;
pub use memory::MemoryScope;
pub use memory::MemoryType;
pub use mirrors::MirrorEntry;
pub use mirrors::OFFICIAL_ID;
pub use mirrors::MirrorGroup;
pub use mirrors::MirrorKind;
pub use mirrors::MirrorsSettings;
pub use mirrors::apply_github_prefix;
pub use mirrors::builtin_mirrors;
pub use mirrors::github_prefix;
pub use mirrors::load_mirrors;
pub use mirrors::merge_into_settings;
pub use mirrors::mirror_env;
pub use mirrors::normalize_mirrors;
pub use provider::HttpModelProvider;
pub use provider::reasoning_parameter_status;
pub use runtime::*;
pub use runtime_paths::*;
pub use skill_router::*;
pub use task_manager::*;
pub use update::UpdateCheckResult;
pub use update::check_for_update;
