const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && /tauri|index/i.test(t.url || '')) || list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
await new Promise((r) => ws.addEventListener('open', r));
await send('Runtime.enable', {}); await send('Page.enable', {});
const ev = async (x) => { try { const r = await send('Runtime.evaluate', { expression: x, awaitPromise: true, returnByValue: true }); if (r.result.exceptionDetails) return 'EXC'; return r.result.result.value; } catch { return null; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
console.log('传输状态(桥)=' + await ev("JSON.stringify(window.__transportDebug ? window.__transportDebug() : null)"));
console.log('自检=' + await ev("(async function(){ try { return String(await window.__sessionDebug && ''); } catch(e){ return ''; } })()"));
await ev("(function(){ localStorage.removeItem('coomi.transport.v1'); return 1; })()");
await send('Page.reload', { ignoreCache: true });
await sleep(11000);
console.log('复位后传输=' + await ev("JSON.stringify(window.__transportDebug ? window.__transportDebug() : null)"));
console.log('会话=' + await ev("(function(){ var d=window.__sessionDebug.read(); return JSON.stringify({len:d.messagesLen, streaming:d.streaming}); })()"));
ws.close();
