const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && /tauri|index/i.test(t.url || '')) || list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
await new Promise((r) => ws.addEventListener('open', r));
await send('Runtime.enable', {});
const ev = async (x) => { const r = await send('Runtime.evaluate', { expression: x, awaitPromise: true, returnByValue: true }); if (r.result.exceptionDetails) return 'EXC'; return r.result.result.value; };
const d = JSON.parse(await ev('JSON.stringify(window.__sessionDebug.read())'));
console.log('sid=' + String(d.sessionId).slice(0, 8) + ' len=' + d.messagesLen + ' streaming=' + d.streaming);
console.log('tail=' + JSON.stringify(d.messagesTail.map((m) => m.kind + ':' + String(m.text || '').replace(/\s+/g, ' ').slice(0, 18))));
console.log('shrinks=' + await ev("JSON.stringify((window.__sessionDebug.journal()||[]).filter(function(e){return e.phase==='SHRINK';}))"));
console.log('bubbles=' + await ev("document.querySelectorAll('[data-msg-id],[class*=bubble]').length"));
ws.close();
