const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && /tauri|index/i.test(t.url || '')) || list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
await new Promise((r) => ws.addEventListener('open', r));
await send('Runtime.enable', {});
const ev = async (x) => { const r = await send('Runtime.evaluate', { expression: x, awaitPromise: true, returnByValue: true }); if (r.result.exceptionDetails) return 'EXC ' + (r.result.exceptionDetails.text||''); return r.result.result.value; };
console.log('A ' + await ev("(async () => { const b = window.__COOMI_BOOT__; const h = { Authorization: 'Bearer ' + b.token }; try { const a = await fetch('http://127.0.0.1:' + b.port + '/api/sessions', { headers: h }); const j = await a.json(); const c = await fetch('http://127.0.0.1:' + b.port + '/api/runtime/installed', { headers: h }); return 'sessions HTTP ' + a.status + ' n=' + ((j.sessions||[]).length) + ' | installed HTTP ' + c.status; } catch (e) { return 'ERR ' + e.message; } })()"));
console.log('B ' + await ev("(function(){ var d = window.__sessionDebug.read(); return JSON.stringify({ keys: Object.keys(d), sid: String(d.sessionId||'').slice(0,8), len: d.messagesLen, streaming: !!d.streaming, transport: d.transport }); })()"));
ws.close();