const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && /tauri|index/i.test(t.url || '')) || list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
await new Promise((r) => ws.addEventListener('open', r));
await send('Runtime.enable', {}); await send('Page.enable', {});
const ev = async (x) => { try { const r = await send('Runtime.evaluate', { expression: x, awaitPromise: true, returnByValue: true }); if (r.result.exceptionDetails) return 'EXC'; return r.result.result.value; } catch { return null; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
console.log('清标记=' + await ev("(function(){ localStorage.removeItem('coomi.transport.v1'); return 'ok'; })()"));
await send('Page.reload', { ignoreCache: true });
await sleep(13000);
console.log('重载后传输=' + await ev("JSON.stringify(window.__transportDebug ? window.__transportDebug() : null)"));
console.log('注入信息=' + await ev("JSON.stringify(window.__COOMI_BOOT__ ? {port:window.__COOMI_BOOT__.port, v:window.__COOMI_BOOT__.version} : null)"));
console.log('会话=' + await ev("(function(){ var d=window.__sessionDebug.read(); return JSON.stringify({sid:String(d.sessionId).slice(0,8), len:d.messagesLen}); })()"));
console.log('切换会话一次（验证主动关闭不再误判）=' + await ev("(function(){ var b=[].slice.call(document.querySelectorAll('button,a,[role=button]')); var hit=b.filter(function(x){ return /新建对话|新对话/.test(((x.getAttribute('aria-label')||'')+' '+(x.textContent||'')).trim()); }); if(hit.length) hit[0].click(); return 'ok'; })()"));
await sleep(4000);
console.log('切换后传输=' + await ev("JSON.stringify(window.__transportDebug ? window.__transportDebug() : null)"));
ws.close();
