import { writeFileSync } from 'node:fs';
const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && /tauri|index/i.test(t.url || '')) || list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
await new Promise((r) => ws.addEventListener('open', r));
await send('Runtime.enable', {}); await send('Page.enable', {});
const shot = await send('Page.captureScreenshot', { format: 'png' });
writeFileSync('shot-now.png', Buffer.from(shot.result.data, 'base64'));
console.log('saved shot-now.png');
const ev = async (x) => { const r = await send('Runtime.evaluate', { expression: x, awaitPromise: true, returnByValue: true }); if (r.result.exceptionDetails) return 'EXC'; return r.result.result.value; };
console.log('viewport=' + await ev("JSON.stringify({w:window.innerWidth,h:window.innerHeight,dpr:window.devicePixelRatio,visible:document.visibilityState,hasFocus:document.hasFocus()})"));
ws.close();
