mod agent;
pub mod artifacts;
mod context;
mod dependency;
mod input_queue;
mod instructions;
mod memory;
pub mod prompt;
mod response_cache;
mod session;
mod session_ext;
mod skill;
mod smart_context;
mod smart_tools;
mod tool_optimizer;
mod types;
mod workflow_runner;
mod workflow_store;

pub use agent::Agent;
pub use agent::AgentError;
pub use agent::DEFAULT_AUTO_COMPACT_MESSAGE_LIMIT;
pub use agent::MAX_AUTO_COMPACT_MESSAGE_LIMIT;
pub use agent::MIN_AUTO_COMPACT_MESSAGE_LIMIT;
pub use context::COMPACTION_HISTORY_LIMIT;
pub use context::COMPACT_PINNED_MAX_TOKENS;
pub use context::CompactionRecord;
pub use context::ContextState;
pub use context::SUMMARIZATION_PROMPT;
pub use context::SUMMARY_PREFIX;
pub use context::compacted_history;
pub use context::compacted_history_with_budget;
pub use context::estimate_request_tokens;
pub use context::normalize_history;
pub use context::retained_user_history;
pub use context::retained_user_history_with_count;
pub use context::trim_history_to_fit;
pub use input_queue::InputQueue;
pub use input_queue::Interjection;
pub use instructions::discover_project_instructions;
pub use session::Session;
pub use session::SessionMode;
pub use session::repair_tool_pairing;
pub use session::SessionStore;
pub use session::SessionSummary;
pub use types::AgentEvent;
pub use types::AgentObserver;
pub use types::ApprovalHandler;
pub use types::Attachment;
pub use types::AutoCompactScope;
pub use types::ChatMessage;
pub use types::CompactionReason;
pub use types::CompactionRequest;
pub use types::CompactionResponse;
pub use types::ContextStatus;
pub use types::ContextWindowSource;
pub use types::DEFAULT_AUTO_COMPACT_FLOOR_TOKENS;
pub use types::DEFAULT_AUTO_COMPACT_PERCENT;
pub use types::DEFAULT_AUTO_COMPACT_RETAIN_TOKENS;
pub use types::FileTransferRequest;
pub use types::ImageContent;
pub use types::InvalidToolCall;
pub use types::LoopState;
pub use types::LoopStatus;
pub use types::ModelCapabilities;
pub use types::ModelProvider;
pub use types::ModelRequest;
pub use types::ModelResponse;
pub use types::ModelStreamObserver;
pub use types::NoopObserver;
pub use types::PlanState;
pub use types::PlanStep;
pub use types::PlanStepStatus;
pub use types::ProviderErrorKind;
pub use types::Quote;
pub use types::attachment_kind;
pub use types::ProviderRequestError;
pub use types::Role;
pub use types::TokenUsage;
pub use types::ToolCall;
pub use types::ToolConcurrency;
pub use types::ToolResult;
pub use types::ToolRuntime;
pub use types::ToolSpec;
pub use types::TurnControl;
pub use artifacts::TurnArtifact;
pub use artifacts::artifact_candidates;
pub use artifacts::artifact_kind;
pub use artifacts::collect_turn_artifacts;
pub use types::UserAskAnswer;
pub use types::UserAskRequest;
pub use types::UserInputAnswer;
pub use types::UserInputOption;
pub use types::UserInputQuestion;
pub use types::UserInputRequest;
pub use types::UserInputResponse;
pub use types::WorkflowOrigin;
pub use types::WorkflowSchedule;
pub use types::WorkflowState;
pub use types::WorkflowStatus;
pub use types::WorkflowStep;
pub use types::WorkflowStepState;
pub use workflow_runner::StepContext;
pub use workflow_runner::StepExecResult;
pub use workflow_runner::StepExecutor;
pub use workflow_runner::WorkflowRunOutcome;
pub use workflow_runner::WorkflowRunner;
pub use workflow_store::WorkflowDocument;
pub use workflow_store::WorkflowEntry;
pub use workflow_store::WorkflowStore;
// StepAction 是 enum，需单独导出
pub use types::StepAction;
// === 第三轮优化：新增模块导出 ===
pub use dependency::ToolDependencyGraph;
pub use memory::{MemoryCategory, MemoryEntry, MemoryStore};
pub use session_ext::{ContextWarmer, SessionMatch, SessionSearchResult};
pub use skill::{AgentSkill, FailureAction, SkillAction, SkillRegistry, SkillStep, builtin_skills};
// === 第四轮优化：智能上下文 + 工具路由 + 响应缓存 ===
pub use response_cache::{CacheConfig, CacheEntry, CacheStats, ResponseCache};
pub use smart_context::{CompressionConfig, ContextCompressor, ContextSummary};
pub use smart_tools::{RouteRequest, RouteResult, ToolCategory, ToolMeta, ToolRouter};
// === 批 5：6 层提示词组装 + 技能按需注入 ===
pub use prompt::DEFAULT_SKILL_CONTEXT_BYTES;
pub use prompt::DEFAULT_SKILL_LIMIT;
pub use prompt::MIN_SKILL_SCORE;
pub use prompt::PromptBuilder;
pub use prompt::PromptLayer;
pub use prompt::ScoredSkill;
pub use prompt::SkillCandidate;
pub use prompt::SkillSelector;
pub use prompt::tokenize as tokenize_terms;
// === 第五轮优化：工具执行性能 ===
pub use tool_optimizer::{
    CacheStats as ToolCacheStats, CachedToolResult, OptimizedToolRuntime, ToolCallFingerprint,
    ToolOptimizer, ToolOptimizerConfig, ToolOutputCompressor, ToolResultCache,
};
