#!/bin/sh
set -eu

COOMI_BUILD_KIT="${COOMI_BUILD_KIT:-/opt/coomi-dev}"
COOMI_TOOLCHAIN_ROOT="${COOMI_TOOLCHAIN_ROOT:-$COOMI_BUILD_KIT/current}"

export COOMI_BUILD_KIT COOMI_TOOLCHAIN_ROOT
export PATH="$COOMI_TOOLCHAIN_ROOT/bin:$COOMI_BUILD_KIT/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export JAVA_HOME="${JAVA_HOME:-$COOMI_TOOLCHAIN_ROOT/jdk}"
export ANDROID_HOME="${ANDROID_HOME:-$COOMI_TOOLCHAIN_ROOT/android-sdk}"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
export COOMI_NDK_HOME="${COOMI_NDK_HOME:-$COOMI_TOOLCHAIN_ROOT/android-ndk}"
export COOMI_NDK_TOOLCHAIN_DIR="${COOMI_NDK_TOOLCHAIN_DIR:-$COOMI_TOOLCHAIN_ROOT/bin}"
export COOMI_ANDROID_CLANG="${COOMI_ANDROID_CLANG:-$COOMI_NDK_TOOLCHAIN_DIR/aarch64-linux-android28-clang}"
export COOMI_ANDROID_AR="${COOMI_ANDROID_AR:-$COOMI_NDK_TOOLCHAIN_DIR/llvm-ar}"
export COOMI_ANDROID_RANLIB="${COOMI_ANDROID_RANLIB:-$COOMI_NDK_TOOLCHAIN_DIR/llvm-ranlib}"
export COOMI_AAPT2="${COOMI_AAPT2:-$COOMI_TOOLCHAIN_ROOT/bin/aapt2}"
export COOMI_ANDROID_JAR="${COOMI_ANDROID_JAR:-$ANDROID_HOME/platforms/android-35/android.jar}"
export COOMI_APKSIGNER="${COOMI_APKSIGNER:-$COOMI_TOOLCHAIN_ROOT/bin/apksigner}"
export COOMI_D8="${COOMI_D8:-$COOMI_TOOLCHAIN_ROOT/bin/d8}"
export COOMI_R8_JAR="${COOMI_R8_JAR:-$COOMI_TOOLCHAIN_ROOT/lib/r8.jar}"
export COOMI_NPM="${COOMI_NPM:-npm}"
export COOMI_CARGO="${COOMI_CARGO:-cargo}"
export COOMI_RUSTUP="${COOMI_RUSTUP:-rustup}"
export GRADLE_USER_HOME="${GRADLE_USER_HOME:-$COOMI_BUILD_KIT/cache/gradle}"
export CARGO_HOME="${CARGO_HOME:-$COOMI_BUILD_KIT/cache/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$COOMI_TOOLCHAIN_ROOT/rustup}"
export CARGO_BUILD_JOBS="${CARGO_BUILD_JOBS:-2}"
export GRADLE_OPTS="${GRADLE_OPTS:--Xmx1536m -Dorg.gradle.workers.max=2}"
