<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { apiGet } from '@/bridge/http'
import { goBack } from '@/bridge/navigation'
import PageHead from '@/components/PageHead.vue'
const router = useRouter()
const now = new Date(); const start = ref(new Date(now.getTime() - 7 * 86400000).toISOString().slice(0,16)); const end = ref(now.toISOString().slice(0,16))
const data = ref<{ input_tokens:number; cached_input_tokens:number; output_tokens:number; total_tokens:number; requests:number; records:Array<{timestamp_ms:number; reasoning_effort:string; total_tokens:number; input_tokens:number; output_tokens:number; elapsed_ms:number}> }>({ input_tokens:0,cached_input_tokens:0,output_tokens:0,total_tokens:0,requests:0,records:[] }); const error=ref(''); const busy=ref(false)
const fmt=(n:number)=>n.toLocaleString('zh-CN'); const time=(n:number)=>new Date(n).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})
async function query(){busy.value=true;error.value='';try{data.value=await apiGet(`/api/usage?from=${Date.parse(start.value)}&to=${Date.parse(end.value)}`)}catch(e){error.value=String(e)}finally{busy.value=false}}
onMounted(query)
</script>
<template><div class="page"><PageHead title="用量统计（实验）" @back="goBack(router,'dashboard')"/><main class="body"><div class="filters"><label>开始<input v-model="start" type="datetime-local"/></label><label>结束<input v-model="end" type="datetime-local"/></label><button class="query" :disabled="busy" @click="query">查询</button></div><p v-if="error" class="error">{{ error }}</p><section class="cards"><div><span>总 Token</span><strong>{{ fmt(data.total_tokens) }}</strong></div><div><span>输入</span><strong>{{ fmt(data.input_tokens) }}</strong></div><div><span>输出</span><strong>{{ fmt(data.output_tokens) }}</strong></div><div><span>请求次数</span><strong>{{ fmt(data.requests) }}</strong></div></section><p class="sec-label">用量流水</p><section class="group"><p v-if="!data.records.length" class="empty">当前时间范围暂无记录</p><div v-for="(r,i) in data.records" :key="i" class="row"><span class="time">{{ time(r.timestamp_ms) }}</span><span class="effort">{{ r.reasoning_effort }}</span><span class="tokens">{{ fmt(r.total_tokens) }} tokens</span></div></section></main></div></template>
<style scoped>.page{display:flex;flex-direction:column;height:100%;background:var(--page)}.body{flex:1;overflow:auto;padding:14px 12px calc(var(--safe-bottom) + 24px);min-width:0}.filters{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,auto);gap:7px;align-items:end;max-width:100%;overflow:hidden}.filters label{display:flex;min-width:0;flex-direction:column;gap:4px;color:var(--text-3);font-size:11px}.filters input{display:block;min-width:0;width:100%;box-sizing:border-box;height:36px;padding:0 6px;border:1px solid var(--border-strong);border-radius:6px;background:var(--bg);color:var(--text);font-size:11px}.query{height:36px;min-width:0;padding:0 10px;border-radius:6px;background:var(--blue);color:#fff;font-size:12px;white-space:nowrap}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}.cards div{padding:12px;border-radius:var(--r-card);background:var(--bg);box-shadow:var(--shadow-1)}.cards span{display:block;color:var(--text-3);font-size:11px}.cards strong{display:block;margin-top:4px;color:var(--text);font-size:18px;font-variant-numeric:tabular-nums}.sec-label{margin:18px 0 6px}.group{overflow:hidden;border-radius:var(--r-card);background:var(--bg);box-shadow:var(--shadow-1)}.row{display:grid;grid-template-columns:1fr auto auto;gap:10px;padding:12px 13px;border-bottom:1px solid var(--border);font-size:12px}.row:last-child{border-bottom:0}.time{color:var(--text-2)}.effort{color:var(--blue)}.tokens{color:var(--text-3);font-variant-numeric:tabular-nums}.empty{padding:16px;color:var(--text-3);font-size:13px}.error{color:var(--danger);font-size:12px}</style>
